### ISSUE TITLE
Create an issue for each "strength" and link to it from the respective strength name in the README

### ISSUE THREAD

**Issue by tcg** [tcg/emoji-strengths#9]
You can see how to make links by looking at the file changes for this merged Pull Request: https://github.com/tcg/emoji-strengths/pull/8/files

**Comment by Nada1996** [comment]
Can I start working on it?

**Comment by tcg** [comment]
@nada1996 Absolutely! Go for it!

**Comment by tcg** [comment]
I’m out and about today, but if you need any help, just comment and I’ll do my best to reply ASAP.

**Comment by tcg** [comment]
Closed by https://github.com/tcg/emoji-strengths/pull/37
